GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.dGFuMw.grtpipvC4HpgNM6mmmbidA8IudgCONBDIA0q3tfVjHA
###




POST http://localhost:4000/token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVGFuYXkiLCJpYXQiOjE2MDEwMDY4OTR9.Az3wklKGo7yhoLZF7--xRKMVR1Tc0NaE3znDbxYiqYo"
    
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
        "name":"tan3",
        "password":"imtanayd"
}


###
POST http://localhost:3000/userreg
Content-Type: application/json

{
    "name":"tan3",
    "password":"imtanayd"
}

###
POST http://localhost:3000/ownreq
Content-Type: application/json

{
        "Shopname":"dasd",
        "description":"asfd",
        "address":"das",
        "timing":"dfdsvcx",
        "imagePath":"dvcxv"
}

###

DELETE  http://localhost:3000/logout
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiJ9.dGFuMw.grtpipvC4HpgNM6mmmbidA8IudgCONBDIA0q3tfVjHA"
}

